New railtie when Rails is define + More
girishso/pluck_to_hash pull request #26
Opened 2018-01-04 03:42 UTC by ericproulx

Hi,

First of all, Happy new year! I added a couple of thing in your gem.

1. Added a `Railtie` for `Rails`. It seems to be faster to load (well in my app it's way faster based on `bumbler` stats)
2. Updated your travis for multiple ruby versions
3. Added rubocop and run it with auto-correct and auto-gen-config
4. Added `# frozen_literal_string: true`
5. Removed some specs that were not working. It was all about StatementInvalid

Enjoy!

2018-01-23 00:13 UTC, girishso requested changes
Hey, Thanks for the PR and Happy New Year!

Good to see addition of rubocop and Railtie.

Everything looks good to me, except the removal of few specs.  Please add back the specs and so I can merge your PR.

2018-01-23 00:13 UTC, girishso commented on spec/pluck_to_struct_spec.rb
> -    context 'the model does not have the attribute specified' do
Please add back this spec

2018-01-23 00:13 UTC, girishso commented on spec/support/shared_examples.rb
> -  context 'the model does not have the attribute specified' do
Please add back this spec

2018-01-23 00:13 UTC, girishso commented on spec/support/shared_examples.rb
> -    context 'the model does not have the attribute specified' do
Please add back this spec

2018-01-23 03:23 UTC, ericproulx commented
I restored the specs but they ain't passing. Related to Rails 5.1 ?

2018-01-23 04:00 UTC, ericproulx commented
Well, the specs ain't working for active record 5.0 and above.

2018-03-08 18:48 UTC, ericproulx commented
Hey, have you seen my last message ?

2020-12-29 21:13 UTC, closed without merging